# Construcción de un Léxico

In [8]:
sentence = """Chile ganó la Copa América el año 2015 y el año 2016"""
x = sentence.split()
print(x)

['Chile', 'ganó', 'la', 'Copa', 'América', 'el', 'año', '2015', 'y', 'el', 'año', '2016']


In [9]:
y = str.split(sentence)
print(y)

['Chile', 'ganó', 'la', 'Copa', 'América', 'el', 'año', '2015', 'y', 'el', 'año', '2016']


In [22]:
sentence = """La selección de Chile ganó la Copa América el año 2015 en Chile y el año 2016 en EEUU."""
token_sequence = str.split(sentence)
vocab = sorted(set(token_sequence))
print(vocab)

['2015', '2016', 'América', 'Chile', 'Copa', 'EEUU.', 'La', 'año', 'de', 'el', 'en', 'ganó', 'la', 'selección', 'y']


In [11]:
#El numero de tokens en la oracion
num_tokens = len(token_sequence)
print(num_tokens)

#La cantidad de tokens en el léxico
vocab_size = len(vocab)
print(vocab_size)

19
15


## Vectorización de un documento

* **One Hot Vectors**


* **Bolsa de Palabras Binaria**

In [12]:
import numpy as np

onehot_vectors = np.zeros((num_tokens, vocab_size), int)

for i, word in enumerate(token_sequence):
    onehot_vectors[i, vocab.index(word)] = 1

' '.join(vocab)

print(onehot_vectors)
print(onehot_vectors.shape)

[[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]]
(19, 15)


In [13]:
#Representación vectorial de una frase
rep_vec=np.transpose(onehot_vectors)
print(rep_vec)
print(rep_vec.shape)

[[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]]
(15, 19)


In [16]:
import pandas as pd

df = pd.DataFrame(onehot_vectors, columns=vocab)
df

2015  2016  América  Chile  Copa  EEUU.  La  año  de  el  en  ganó  la  \
0      0     0        0      0     0      0   1    0   0   0   0     0   0   
1      0     0        0      0     0      0   0    0   0   0   0     0   0   
2      0     0        0      0     0      0   0    0   1   0   0     0   0   
3      0     0        0      1     0      0   0    0   0   0   0     0   0   
4      0     0        0      0     0      0   0    0   0   0   0     1   0   
5      0     0        0      0     0      0   0    0   0   0   0     0   1   
6      0     0        0      0     1      0   0    0   0   0   0     0   0   
7      0     0        1      0     0      0   0    0   0   0   0     0   0   
8      0     0        0      0     0      0   0    0   0   1   0     0   0   
9      0     0        0      0     0      0   0    1   0   0   0     0   0   
10     1     0        0      0     0      0   0    0   0   0   0     0   0   
11     0     0        0      0     0      0   0    0   0   0   1     0   0   
12     0     0        0      1     0      0   0    0   0   0   0     0   0   
13     0     0        0      0     0      0   0    0   0   0   0     0   0   
14     0     0        0      0     0      0   0    0   0   1   0     0   0   
15     0     0        0      0     0      0   0    1   0   0   0     0   0   
16     0     1        0      0     0      0   0    0   0   0   0     0   0   
17     0     0        0      0     0      0   0    0   0   0   1     0   0   
18     0     0        0      0     0      1   0    0   0   0   0     0   0   

    selección  y  
0           0  0  
1           1  0  
2           0  0  
3           0  0  
4           0  0  
5           0  0  
6           0  0  
7           0  0  
8           0  0  
9           0  0  
10          0  0  
11          0  0  
12          0  0  
13          0  1  
14          0  0  
15          0  0  
16          0  0  
17          0  0  
18          0  0

In [19]:
df = pd.DataFrame(onehot_vectors, columns=vocab)
df[df == 0] = ''
df

2015 2016 América Chile Copa EEUU. La año de el en ganó la selección  y
0                                      1                                  
1                                                                     1   
2                                             1                           
3                        1                                                
4                                                        1                
5                                                           1             
6                             1                                           
7                  1                                                      
8                                                1                        
9                                          1                              
10    1                                                                   
11                                                  1                     
12                       1                                                
13                                                                       1
14                                               1                        
15                                         1                              
16         1                                                              
17                                                  1                     
18                                  1

In [23]:
sentence_bow = {}

for token in sentence.split():
    sentence_bow[token] = 1
sorted(sentence_bow.items())

[('2015', 1),
 ('2016', 1),
 ('América', 1),
 ('Chile', 1),
 ('Copa', 1),
 ('EEUU.', 1),
 ('La', 1),
 ('año', 1),
 ('de', 1),
 ('el', 1),
 ('en', 1),
 ('ganó', 1),
 ('la', 1),
 ('selección', 1),
 ('y', 1)]

In [24]:
df = pd.DataFrame(pd.Series(dict([(token, 1) for token in sentence.split()])), columns=['sent']).T
df

La  selección  de  Chile  ganó  la  Copa  América  el  año  2015  en  y  \
sent   1          1   1      1     1   1     1        1   1    1     1   1  1   

      2016  EEUU.  
sent     1      1

In [29]:
sentences = """Chile ganó la Copa América los años 2015 y 2016.\n"""
sentences += """Chile no fué al mundial.\n"""
sentences += "En los partidos de fútbol no hay público en las galerias.\n"
sentences += """En el 2015 y 2016 no estaba en Chile.\n"""
sentences += """Puede que Chile vaya al mundial"""
corpus = {}

for i, sent in enumerate(sentences.split('\n')):
    corpus['sent{}'.format(i)] = dict((tok, 1) for tok in sent.split())
df = pd.DataFrame.from_records(corpus).fillna(0).astype(int).T
df

Chile  ganó  la  Copa  América  los  años  2015  y  2016.  ...  las  \
sent0      1     1   1     1        1    1     1     1  1      1  ...    0   
sent1      1     0   0     0        0    0     0     0  0      0  ...    0   
sent2      0     0   0     0        0    1     0     0  0      0  ...    1   
sent3      0     0   0     0        0    0     0     1  1      0  ...    0   
sent4      1     0   0     0        0    0     0     0  0      0  ...    0   

       galerias.  el  2016  estaba  Chile.  Puede  que  vaya  mundial  
sent0          0   0     0       0       0      0    0     0        0  
sent1          0   0     0       0       0      0    0     0        0  
sent2          1   0     0       0       0      0    0     0        0  
sent3          0   1     1       1       1      0    0     0        0  
sent4          0   0     0       0       0      1    1     1        1  

[5 rows x 31 columns]

**¿Podremos medir la similitud entre los documentos?**

In [31]:
df.Chile

sent0    1
sent1    1
sent2    0
sent3    0
sent4    1
Name: Chile, dtype: int32

In [32]:
df.T.sent0

Chile        1
ganó         1
la           1
Copa         1
América      1
los          1
años         1
2015         1
y            1
2016.        1
no           0
fué          0
al           0
mundial.     0
En           0
partidos     0
de           0
fútbol       0
hay          0
público      0
en           0
las          0
galerias.    0
el           0
2016         0
estaba       0
Chile.       0
Puede        0
que          0
vaya         0
mundial      0
Name: sent0, dtype: int32

In [33]:
df = df.T
df.sent0.dot(df.sent1)

1

In [34]:
df.sent0.dot(df.sent3)

2

In [38]:
[(k, v) for (k, v) in (df.sent0 & df.sent3).items() if v]

[('2015', 1), ('y', 1)]