# Clase 13 XBGoost

In [1]:
import xgboost as xgb
import numpy as np
from sklearn.datasets import fetch_covtype
from sklearn.model_selection import train_test_split
import time
cov = fetch_covtype()
X = cov.data
y = cov.target

In [2]:
X.shape

(581012, 54)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,train_size=0.75,random_state=42)
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)
num_round = 300

In [7]:
param = {'objective': 'multi:softmax',
'num_class': 8,
'tree_method': 'hist'}
tmp = time.time()
cpu_res = {}
xgb.train(param, dtrain, num_round, evals=[(dtest, 'test')],evals_result=cpu_res)

print("Tiempo de entrenamiento en CPU: %s segundos" % (str(time.time() - tmp)))

[0]	test-mlogloss:1.47290
[1]	test-mlogloss:1.20547
[2]	test-mlogloss:1.03109
[3]	test-mlogloss:0.91091
[4]	test-mlogloss:0.82473
[5]	test-mlogloss:0.75971
[6]	test-mlogloss:0.70965
[7]	test-mlogloss:0.67044
[8]	test-mlogloss:0.63918
[9]	test-mlogloss:0.61292
[10]	test-mlogloss:0.59139
[11]	test-mlogloss:0.57449
[12]	test-mlogloss:0.55924
[13]	test-mlogloss:0.54745
[14]	test-mlogloss:0.53699
[15]	test-mlogloss:0.52533
[16]	test-mlogloss:0.51629
[17]	test-mlogloss:0.50918
[18]	test-mlogloss:0.50352
[19]	test-mlogloss:0.49591
[20]	test-mlogloss:0.49065
[21]	test-mlogloss:0.48641
[22]	test-mlogloss:0.48186
[23]	test-mlogloss:0.47754
[24]	test-mlogloss:0.47460
[25]	test-mlogloss:0.47175
[26]	test-mlogloss:0.46896
[27]	test-mlogloss:0.46370
[28]	test-mlogloss:0.46079
[29]	test-mlogloss:0.45770
[30]	test-mlogloss:0.45459
[31]	test-mlogloss:0.44983
[32]	test-mlogloss:0.44601
[33]	test-mlogloss:0.44328
[34]	test-mlogloss:0.44163
[35]	test-mlogloss:0.44001
[36]	test-mlogloss:0.43727
[37]	test-m

In [8]:
param = {'objective': 'multi:softmax',
'num_class': 8,
'tree_method': 'gpu_hist'}
gpu_res = {}
tmp = time.time()
xgb.train(param, dtrain, num_round, evals=[(dtest, 'test')],evals_result=gpu_res)
print("Tiempo de entrenamiento en GPU: %s segundos" % (str(time.time() - tmp)))

[15:49:56] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-07593ffd91cd9da33-1\xgboost\xgboost-ci-windows\src\learner.cc:339: No visible GPU is found, setting `gpu_id` to -1


XGBoostError: [15:49:56] C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-07593ffd91cd9da33-1\xgboost\xgboost-ci-windows\src\gbm\gbtree.cc:625: Check failed: common::AllVisibleGPUs() >= 1 (0 vs. 1) : No visible GPU is found for XGBoost.

3.1 XGBoost como modelo de Clasificación

In [9]:
from sklearn import datasets
from sklearn import metrics
from sklearn.model_selection import train_test_split
import xgboost as xgb
dataset = datasets.load_wine()

X = dataset.data; y = dataset.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [10]:
np.unique(y)

array([0, 1, 2])

In [11]:
model = xgb.XGBClassifier(n_estimators=2, max_depth=2, learning_rate=1,objective='multi:softprob')
model.fit(X_train, y_train)
print(model)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=2, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=2, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)


In [12]:
y_pred = model.predict(X_test)
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.96      0.98        27
           2       0.91      1.00      0.95        10

    accuracy                           0.98        45
   macro avg       0.97      0.99      0.98        45
weighted avg       0.98      0.98      0.98        45

[[ 8  0  0]
 [ 0 26  1]
 [ 0  0 10]]
